[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = false
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[logger]
level = "warning"
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"

[client]
caching = true
displayEnabled = true
toolbarMode = "minimal"
